{% set name = "h5pyd" %}
{% set version = "0.12.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/h5pyd-{{ version }}.tar.gz
  sha256: c70a4800368d4ebfd1c89b9fd430d13310f59cfd7817db4f1b5fadb6e81a89ac

build:
  entry_points:
    - hsinfo = h5pyd._apps.hsinfo:main
    - hsls = h5pyd._apps.hsls:main
    - hstouch = h5pyd._apps.hstouch:main
    - hsacl = h5pyd._apps.hsacl:main
    - hsdel = h5pyd._apps.hsdel:main
    - hsrm = h5pyd._apps.hsdel:main
    - hsget = h5pyd._apps.hsget:main
    - hsload = h5pyd._apps.hsload:main
    - hsconfigure = h5pyd._apps.hsconfigure:main
    - hscopy = h5pyd._apps.hscopy:main
    - hscp = h5pyd._apps.hscopy:main
    - hsmv = h5pyd._apps.hsmv:main
    - hsdiff = h5pyd._apps.hsdiff:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pkgconfig
    - pip
  run:
    - python >=3.6
    - numpy >=1.17.3
    - requests-unixsocket
    - pytz
    - pyjwt
    - msrestazure
    - cryptography
    - google-api-python-client
    - google-auth-oauthlib ==0.5.3
    - google-auth <2.0dev
    - adal

test:
  imports:
    - h5pyd
  commands:
    - pip check
    - hsinfo --help
    - hsls --help
    - hstouch --help
    - hsacl --help
    - hsdel --help
    - hsrm --help
    - hsget --help
    - hsload --help
    - hscopy --help
    - hscp --help
    - hsmv --help
    - hsdiff --help
  requires:
    - pip
    - h5py

about:
  home: http://github.com/HDFGroup/h5pyd
  summary: h5py compatible client lib for HDF REST API
  license: LicenseRef-HDF5
  license_file:
    - COPYING

extra:
  recipe-maintainers:
    - ocefpaf
