{% set name = "h5pyd" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/h5pyd-{{ version }}.tar.gz
  sha256: 0f0b2b166c2f8573d7746ab2fd21edf6065b37b700616c16b76d5e5b023b08e6

build:
  entry_points:
    - hsinfo = h5pyd._apps.hsinfo:main
    - hsls = h5pyd._apps.hsls:main
    - hstouch = h5pyd._apps.hstouch:main
    - hsacl = h5pyd._apps.hsacl:main
    - hsdel = h5pyd._apps.hsdel:main
    - hsrm = h5pyd._apps.hsdel:main
    - hsget = h5pyd._apps.hsget:main
    - hsload = h5pyd._apps.hsload:main
    - hsconfigure = h5pyd._apps.hsconfigure:main
    - hscopy = h5pyd._apps.hscopy:main
    - hscp = h5pyd._apps.hscopy:main
    - hsmv = h5pyd._apps.hsmv:main
    - hsdiff = h5pyd._apps.hsdiff:main
    - hsstat = h5pyd._apps.hsstat:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pkgconfig
    - pip
  run:
    - python >=3.6
    - numpy >=1.17.3
    - requests-unixsocket
    - pytz
    - pyjwt
    - msrestazure
    - cryptography
    - google-api-python-client
    - google-auth-oauthlib
    - google-auth <2.0dev
    - adal

test:
  imports:
    - h5pyd
  commands:
    - pip check
    - hsinfo --help
    - hsls --help
    - hstouch --help
    - hsacl --help
    - hsdel --help
    - hsrm --help
    - hsget --help  # requires h5py
    # - hsload --help  # non-zero return
    # - hsconfigure --help  # requires user input
    - hscopy --help
    - hscp --help
    # - hsmv --help  # non-zero return
    # - hsdiff --help  # non-zero return
    - hsstat --help
  requires:
    - pip
    - h5py

about:
  home: http://github.com/HDFGroup/h5pyd
  summary: h5py compatible client lib for HDF REST API
  license: LicenseRef-HDF5
  license_file:
    - COPYING

extra:
  recipe-maintainers:
    - ocefpaf
